### ISSUE TITLE
Resolving the org.jboss.auto dependency

### ISSUE THREAD

**Issue by bitwerk** [hal/elemento#1]
When trying to build elemento, maven are unable to resolve org.jboss.auto:apt-tools:jar:0.0.1. Is there a separate repo I need to add or something?

**Comment by hpehl** [comment]
You need to add the following repository (which is already in Elemento's POM):

```xml
<repository>
        <id>jboss-public-repository-group</id>
        <name>JBoss Public Maven Repository Group</name>
        <url>https://repository.jboss.org/nexus/content/groups/public/</url>
</repository>
```
