### ISSUE TITLE
Migrate to Elemental2 once it's publicly available

### ISSUE THREAD

**Issue by hpehl** [hal/elemento#11]
Link to the latest? Elemental2 snapshot: https://oss.sonatype.org/service/local/repositories/google-releases/content/com/google/gwt/elemental2-experimental/16-06-30/elemental2-experimental-16-06-30.jar

**Comment by dnouls** [comment]
I could really use this! My code is already depending on Elemental2 but I could use a builder and templating mechanism that is ready for it.

**Comment by hpehl** [comment]
Where can I get the latest Elemental2 version? There's little to no information about it :-(

**Comment by dnouls** [comment]
I'm using the experimental elemental2 release. Available through this maven dependency:
<dependency>
  <groupId>com.google.gwt</groupId>
  <artifactId>elemental2-experimental</artifactId>
  <version>16-06-30</version>
</dependency>

I guess you want to wait for the final release.

**Comment by remarkNS** [comment]
The latest version of Elemental 2 : https://search.maven.org/#search%7Cga%7C1%7Ccom.google.elemental2

Announced here:
https://groups.google.com/forum/#!topic/google-web-toolkit-contributors/MyGZ4-ASG-Y

**Comment by hpehl** [comment]
So I guess no more excuses ;-) Will try to release a new version based on Elemental2 asap.

**Comment by dnouls** [comment]
looking forward to it

**Comment by hpehl** [comment]
Released [0.3.0](https://github.com/hal/elemento/releases/tag/0.3.0) based on Elemental2. The release is also be available in the public JBoss maven repository.
