### ISSUE TITLE
Question: can I use widgets in combination with Elemento/templating ?

### ISSUE THREAD

**Issue by dnouls** [hal/elemento#12]
I want to migrate my code that is depending on UiBinder and some custom widgets to Elemento. I really like the design. 

What is not clear to me if it is possible to still use some old widgets inside an Elemento template ? Or if there is a way to insert a widget as a child of an HTMLElement somehow ?

All I am missing is support for a binding framework (2-way) in combination with javax.validation support and I think I will have a nice replacement for the old GWT widgets and features.

**Comment by hpehl** [comment]
Using widgets w/ HTML template should work. Take a look at https://github.com/hal/elemento#data-elements. You'll need a field w/ an initialiser, something like

```java
@Templated("MyApp.html#root")
abstract class MyApp implements IsElement {

    @DataElement MyWidget myWidget = new MyWidget();
}
```

if a field initialiser doesn't work, you can also use methods.

Regarding binding and validation, I recommend to take a look at [Errai](http://erraiframework.org/). I designed Elemento to be only a small toolkit around Elemental. If you want more, you'll have to switch ;-)

**Comment by dnouls** [comment]
Thanks for the info, I really like your work.

I am a bit afraid of Errai because it brings in soo much more than I need.

**Comment by remarkNS** [comment]
Yes I agree with @dnouls, Errai should be much smaller and simpler (without the need to use EE server - Wildfly 10+ ?) in order to be attractive. The last time I looked into it, there was no easy way to run it on the Tomcat. There are some info that this should be possible ("somehow", "somebody did it" and made a github project, but that did not working when I tried), and even then you have to bring so much (EE) jars that it's way too complex. I think it should be possible to drop the war on the Tomcat by default, and if you really need EE stuff than you should be able to use "EE Errai". Simply put: Errai should be "SE" by default and not "EE" by default.

**Comment by hpehl** [comment]
Errai is best when you want to implement bigger enterprise SPAs. It has advanced features such as data synchronisation, annotations based validation or two way data binding. However it comes with some dependencies (one of them is WildFly, EE APIs). 

I designed Elemento as an alternative in case you're just want to use GWT Elemental and support for simple HTML templates. However you have to implement or integrate all other goodies on your own.

**Comment by remarkNS** [comment]
I know that @hpehl, but still my personal opinion is that "JPA in the Browser", "CDI in the Browser" and other "EE" stuff should be optional. You don't need them for validation and data binding. That's what I think when I say it's over complex by default. Errai is great product, but EE features should not be mandatory, they should be optional. BTW your work (Elemento) is great as well ! I will probably use it in the future with my own validation, binding and other stuff on top of it.

**Comment by hpehl** [comment]
Thanks. 

Feel free to open a discussion at [1] or file an issue at [2]. Usually the Errai devs are open for improvements and ideas from the community. 

[1] https://developer.jboss.org/en/errai?view=discussions
[2] https://issues.jboss.org/projects/ERRAI/summary

**Comment by hpehl** [comment]
I close this issue, after discussions about the different frameworks and their main focus. Please reopen if you disagree.
