### ISSUE TITLE
Elements.Builder Inheritence?

### ISSUE THREAD

**Issue by gte619n** [hal/elemento#2]
Hello! So I've finally resolved all my 2.8 funny business and have begun using Elemento in my application. I really like the API; however, I was wondering why Elements.Builder is final?

I would like to extend Builder to have some more application specific helpers. In a bunch of places, I create a lot of `nav` elements and then there's the case of a list of links, which could nicely be wrapped, helping reduce the boiler plate even further.

I've seen people use recurring generics to have [inheritable builders](http://stackoverflow.com/a/17165079/836267). Would this be something that Elemento could handle?

Thanks for such a helpful library!

**Comment by hpehl** [comment]
Making the builder non-final lgtm. How about submitting a PR? Then we could further discuss the changes there.

**Comment by gte619n** [comment]
Hey Harald,

I'll throw up a PR this weekend.

Thanks,

E

**Comment by gte619n** [comment]
Hey Harald,

Here's the PR: https://github.com/hal/elemento/pull/3

Thanks,

E

**Comment by gte619n** [comment]
So I had a better idea about default implementation. I closed the previous PR and have this one: https://github.com/hal/elemento/pull/4

**Comment by hpehl** [comment]
Merged https://github.com/hal/elemento/pull/3
