### ISSUE TITLE
Deploy to maven central

### ISSUE THREAD

**Issue by ibaca** [hal/elemento#21]

**Comment by ibaca** [comment]
What do you think about deploying this lib to maven central?

**Comment by hpehl** [comment]
I used to deploy some older project to maven central. Need to check how to configure the POM. Usually I use jboss-parent POM which sets everything up to deploy to the public JBoss repo.

**Comment by ibaca** [comment]
I already update RxGWT hehe now that EventType is here! but I'll need to wait for this project to be deployed to central 😉.

Also, why don't you use SNAPSHOTs versions? 😞 I see that you per-release branches wich might end up in conflict if you use SNAPSHOTS with versions, but if this is the problem you can just use HEAD-SNAPSHOT. The HEAD-SNAPSHOT also make it easier other libs or example project to keep it always in the last SNAPSHOT.
