### ISSUE TITLE
Key.match() method doesn't work with Safari

### ISSUE THREAD

**Issue by yadavharsh** [hal/elemento#29]
The following code breaks in Safari, as KeyboardEvent.key is not supported in Safari (https://www.w3schools.com/jsref/event_key_key.asp):
```
if (!Key.Enter.match(event)) {
     doStuff();
}
```

Is there a work-around?

Thanks,
Harsh

**Comment by hpehl** [comment]
According to https://caniuse.com/#feat=keyboardevent-key `KeyboardEvent.key` is supported in the latest Safari version. Do you use an older version (< 10.1)? If so please upgrade or use something like https://github.com/cvan/keyboardevent-key-polyfill.

**Comment by yadavharsh** [comment]
That's right I have Version 10.0.3 (12602.4.8), which is not that old though. But looks like polyfill will be the only approach in this case to support existing users.
