### ISSUE TITLE
Maven Dependency Conflict; MoreTypes.asTypeElement() method signature changed

### ISSUE THREAD

**Issue by tyler-ham** [hal/elemento#33]
I am experiencing a Maven dependency conflict between `hal/elemento` and `intendia-oss/autorest`.

The `hal/elemento` template processor relies on auto-common 0.3, while `intendia-oss/autorest` relies on auto-common 0.4. In my project, Maven ends up using the 0.4 version of auto-common, but because of a method signature change, the `hal/elemento` TemplatedProcessor crashes with `java.lang.NoSuchMethodError`. The method signature of `MoreTypes.asTypeElemen()` changed between auto-common 0.3 and 0.4.

Relevant `intendia-oss/autorest` dependency tree:
```
com.intendia.gwt.autorest:autorest-processor:jar:0.6:provided
+- com.google.auto:auto-common:jar:0.4:provided
```

Relevant `hal/elemento` dependency tree:
```
org.jboss.gwt.elemento:elemento-template:gwt-lib:HEAD-SNAPSHOT
+- com.google.auto.service:auto-service:jar:1.0-rc2:compile
   \- com.google.auto:auto-common:jar:0.3:compile
```

Method signature in auto-common 0.3:
`public static TypeElement asTypeElement(Types types, TypeMirror mirror)`

Method signature in auto-common 0.4:
`public static TypeElement asTypeElement(TypeMirror mirror)`

(Here is the commit that implemented the change: https://github.com/google/auto/commit/a428e7bb2c2ce1c13b47d1e43128a1c67c397f21#diff-117761445d686cc88f0b75d965af5a1a)

In my project, I can explicitly set the auto-common dependency to either 0.3 or 0.4. However, when I set it to 0.3, the `intendia-oss/autorest` processor similarly breaks with `java.lang.NoSuchMethodError` since it is using the newer method signature for `MoreTypes.asTypeElement()`.

There are several lines in `TemplatedProcessor.java` that call `MoreTypes.asTypeElement()`. It appears that deleting the first parameter from these calls fixes the problem when used with auto-common 0.4.

What is the best practice for dealing with this type of conflict? Would it be reasonable for `hal/elemento` to explicitly set its auto-common dependency to 0.4 and update the `MoreTypes.asTypeElement()` calls to match? If so, I can submit a pull request.

One alternative is suggesting that `intendia-oss/autorest` downgrade its auto-common dependency to 0.3 instead of 0.4, but I feel better pushing a project like `hal/elemento` forward rather than `intendia-oss/autorest` backwards.

Are there any other solutions I'm missing that I could implement in any of these projects (or my own)?

**Comment by ibaca** [comment]
Ups! hehe we (both projects) really need to shade this dependency (as auto-common suggest) hehe 👍 we'll fix it in the next release in both projects.

**Comment by ibaca** [comment]
Uhm, but I see, but you applied the shade plugin 4month ago but, then... what is this conflict? should be something wrong. Maybe the final pom still includes the dependency? shaded dependencies should be removed from the pom. Not sure... but something is wrong or the conflict will not appear.

**Comment by ibaca** [comment]
Ok, I think I have found the problem. You are applying the shade plugin but the plugin by default just copy all your dependencies into the jar to create an uber-jar which is NOT what you want. You have actually partially configured the exclusion (aka. the lib not to be shared) but or it is obsolete or it has not been correctly configured to match the group:artifact coordinates of the not-to-be-shaded packages. And finally, which is the actual problem here, it needs to relocate the conflicting packages, in this case, auto-service and auto-common classes. If you do not do that you are just copying the class file in your jar so it ends up conflicting anyway.

**Comment by hpehl** [comment]
Yes that's right, my bad. I'm going to re-configure the shade plugin for Elemento.
