### ISSUE TITLE
Support for Dagger (or any other type of) injection

### ISSUE THREAD

**Issue by tyler-ham** [hal/elemento#36]
The TemplateProcessor currently adds injection annotations only if GIN is in the classpath. However, GIN is no longer maintained and the movement appears to be towards Dagger 2 as an annotation processor-based replacement.

However, when I switch to Dagger and remove GIN as a dependency, Elemento's TemplatedProcessor no longer generates Templated_* classes with the injection annotations.

## Workaround

I can keep GIN as a dependency in my project in the meantime, even though it is only being used to indicate to Elemento's TemplatedProcessor that the inject annotation should be applied to generated template classes.

## Proposed Change

I'd like to propose the following change in Elemento's `Templated` annotation and the `TemplatedProcessor`.

Add an `injectiable` attribute on the `Templated` annotation:

```java
public @interface Templated {
    
    enum Injectable { TRUE, FALSE, IF_GIN_PRESENT };
    
    String value() default "";
    Injectable injectable() default Injectable.IF_GIN_PRESENT;
}
```

And then in TemplatedProcessor,

```java
String inject = ginInClasspath() ? "@javax.inject.Inject" : "";
```

becomes something determined for each type

```java
boolean isInjectable = templated.injectable() == Injectable.TRUE
        || (templated.injectable() == Injectable.IF_GIN_PRESENT && ginInClasspath());
String inject = isInjectable ? "@javax.inject.Inject" : "";
```

## Notes

This would maintain backwards compatibility for existing Templated classes that rely on the IF_GIN_PRESENT-type functionality, but would also add the ability to explicitly declare whether (or not) to include the inject annotation.

An alternative would be to make the `injectable` attribute a simple boolean defaulting to false where `true` means to include the Inject annotation and `false` means to exclude it. This would be a breaking change that no longer checks for GIN in the classpath. Any classes relying on GIN would then need to explicitly declare `injectable=true`.

If one of these approaches seems reasonable to you, I would be happy to put together a pull request.

**Comment by hpehl** [comment]
Adding support for Dagger sounds reasonable. What if we extend the IF_GIN_PRESENT-type functionality to also look for other DI frameworks like Dagger: 

```java
public class TemplatedProcessor extends AbstractProcessor {
    
    private static final String[] DEPENDENCY_INJECTION_FRAMEWORKS = {
            "dagger.Component",
            "com.google.gwt.inject.client.GinModule",
    };

    @Override
    protected boolean onProcess(Set<? extends TypeElement> annotations,  RoundEnvironment roundEnv) {
        ...
        String inject = diInClasspath() ? "@javax.inject.Inject" : "";
        ...
    }

    private boolean diInClasspath() {
        for (String clazz : DEPENDENCY_INJECTION_FRAMEWORKS) {
            try {
                if (getClass().getClassLoader().loadClass(clazz) != null) {
                    return true;
                }
            } catch (ClassNotFoundException ignore) {}
        }
        return false;
    }
}
```

Don't know what the "entrypoint" for Dagger is, but `dagger.Component` seems reasonable to me.

**Comment by tyler-ham** [comment]
That could work. I know adding new dependency injection frameworks isn't a frequent event, but having to explicitly add each one in a hardcoded list seems bad to me. I'm just imagining someone else still running into the same problem if another dependency injection framework comes along. So I prefer a solution that allows the developer to explicitly declare whether to include the Inject annotation.

Could we do both the extended framework list and allow for explicit declaration of the behavior?

```java
enum Injectable { TRUE, FALSE, IF_DI_DETECTED }
````

The default IF_DI_DETECTED value would work as you described, but TRUE and FALSE would allow a developer to explicitly define the behavior if the detection list becomes outdated.

**Comment by hpehl** [comment]
The intention behind the hard-coded list is that users should not bother about support for common DI frameworks. Kind of "convention over configuration". But having a way to say explicitly what you want sounds good to me. 

If you could submit this in a PR, that would be great.

**Comment by hpehl** [comment]
Fixed by https://github.com/hal/elemento/commit/fabd32b35066d8ba8499394efa29b12cccbd526f
