### ISSUE TITLE
Debugging Clues

### ISSUE THREAD

**Issue by gte619n** [hal/elemento#5]
Hey Harald,

So I've got another enhancement idea. If I've got a bunch of Builders being thrown around, I tend to forget to close things (enough `.end()`). While this is fairly simple to debug, the messaging doesn't give me any indication as to WHICH builder is still open.

In my branch, I've added a String to the default constructor. In the case of an exception getting thrown, it simply prepends this string if it's not null. This way, I can tell where the issue is coming from.

I've been trying to figure out a way to add this automatically, but without any reflection cases it makes it quite difficult. What do you think?

**Comment by hpehl** [comment]
Makes sense to me. Fixed with https://github.com/hal/elemento/commit/32f49c61a50134a3a5e1c8aebba397abcf71fdb2
