### ISSUE TITLE
Multiple Classes

### ISSUE THREAD

**Issue by gte619n** [hal/elemento#6]
One method that I'm adding to all my builders is a css( String... classes) method. I'm just joining the class names using Guava at the moment, but I think this is probably something we should handle in the Builder. PR?

**Comment by hpehl** [comment]
You can already pass multiple classes separated by space: 

```java
Element fooBar = new Elements.Builder().div().css("foo bar").end();
```

results in 

```html
<div class="foo bar"/>
```

**Comment by gte619n** [comment]
Hey Harald,

That's what I've been doing, but I'd really like to do something like:

`div().css( MyCssResource.class1(), MyCssResource.class2() ).end();`

Just a little easier to apply with the GSS stuff.

**Comment by hpehl** [comment]
Ok I see your point. In that case having a var arg method makes sense. Fixed with https://github.com/hal/elemento/commit/32f49c61a50134a3a5e1c8aebba397abcf71fdb2
