### ISSUE TITLE
Cannot find template

### ISSUE THREAD

**Issue by zak905** [hal/elemento#7]
I have given Elemento a try in myproject. I have tried to use HTML templates, but when I compile, the following error is thrown:

Cannot find template "path/to/template". Please make sure the template exists and resides in the source path.

The resource does exist in the path specified.

Does this sound familiar ? anybody have an idea ?

**Comment by hpehl** [comment]
Elements looks for templates in the source path. If you use maven the easiest way is to place the templates in `src/main/resources` using the same hierarchy as the package name. 

Take a look at the [templated](https://github.com/hal/elemento/tree/develop/samples/templated) sample which uses this setup.

**Comment by zak905** [comment]
The error is gone. I was putting it directly into src/main/java. Thanks

**Comment by zak905** [comment]
Maybe this is too much questions, but after trying to compile with gwt compile, i bumped into this issue: 

[ERROR] Errors in 'jar:file:/C:/Users/zakaria/.m2/repository/org/jboss/gwt/elemento/elemento-core/0.1.10/elemento-core-0.1.10.jar!/org/jboss/gwt/elemento/core/Elements.java'
[INFO]             [ERROR] Line 648: No source code is available for type com.google.common.collect.Iterables; did you forget to inherit a required module?
[INFO]          Tracing compile failure path for type 'org.jboss.gwt.elemento.core.Elements'

Help would be much appreciated.

**Comment by zak905** [comment]
I found this issues on GWT/Guava repositories:

[](https://github.com/google/guava/issues/193)
[](https://github.com/gwtproject/gwt/issues/8989)

it seems like a Java 8 problem.

**Comment by hpehl** [comment]
Thanks for the research. In the meantime I did some version upgrades in the POMs. I"m going to release 0.1.12 soon.

**Comment by hpehl** [comment]
I just released Elemento 0.2 which should fix the issue.

**Comment by hpehl** [comment]
Since there are no further comments on this issue, I assume it's fixed. Please reopen if not.
