### ISSUE TITLE
CSS glitch in samples (missing checkbox)

### ISSUE THREAD

**Issue by cristian-spiescu** [hal/elemento#71]
The samples are missing the (visual) checkbox of Todo entries. The element does exist, because clicking the empty space, toggles the element. So it seems to be only a visual issue.

![image](https://user-images.githubusercontent.com/4469897/66253317-20409400-e76f-11e9-9133-5c0a59d642b6.png)

I think it should look like this:

![image](https://user-images.githubusercontent.com/4469897/66253323-3ea68f80-e76f-11e9-9ecd-59d4d4beb8dd.png)

**Comment by hpehl** [comment]
Fixed by e43ff90
