### ISSUE TITLE
Move templates to crysknife

### ISSUE THREAD

**Issue by hpehl** [hal/elemento#80]
I plan to move the templating part of Elemento to [Crysknife](https://github.com/treblereel/crysknife). Crysknife already contains most of the [templating](https://github.com/treblereel/crysknife/tree/master/ui/templates) code of Elemento, integrates nicely with CDI and offers some extra features like GSS support on top of that. 

The motivation behind this is that we don't want to have two very similar and competing template solutions. Please feel free to comment on this issue if you have a different opinion. 

See also https://github.com/treblereel/crysknife/issues/27.

**Comment by anbuck** [comment]
So this is simply a matter of Elemento referencing Crysknife rather than having the templating code as part of the Elemento library itself? And the templating in Crysknife works the same as it did previously in Elemento, so this is not a breaking change? If so, it definitely makes sense to me.

**Comment by hpehl** [comment]
Yes this is the plan. I'll try to provide a sample w/ Elemento and Crysknife templating soon.
