### ISSUE TITLE
I am facing a bug in Elemento wp Plugin

### ISSUE THREAD

**Issue by JosemariaD** [hal/elemento#84]
After updating my Elemento Plugin, I can no longer edit my pages. 

I saw a message like "Database update process is running in the background.", I don't know what it means.

pls help

**Comment by hpehl** [comment]
Just a few questions: 

1. What is the "Elemento Plugin"?
1. Which pages are you referring to?
1. Elemento is a client-side lib. There's no relation to a database. 

Please try to ask more precisely.

**Comment by JosemariaD** [comment]
Elementor Website Builder.

I want to edit my pages on WordPress using Elemento

**Comment by hpehl** [comment]
Thanks @vegegoku for the clarification. Closing this issue.
