### ISSUE TITLE
Compile on windows10

### ISSUE THREAD

**Issue by masa-oss** [hal/elemento#89]
I was looking for a GWT sample and found this source.

I am very grateful to you for teaching me the latest coding.

I downloaded this and mavened but got a little error.

I modified pom.xml for gwt28.

        <elemental2.version>1.0.0</elemental2.version>
        <elemento.version>1.0.3</elemento.version>

Then I did "mvn gwt: devmode" at gwt28.

I got the following error. (Translating Japanese to English)

Main.java:[33,70]  Can't find symbol.    method  getHash()
     Location: Variable location of type elementary2.dom.Location
Main.java:[34,36] Can't find symbol.    method  getHash()
     Location: Variable location of type elementary2.dom.Location

I'm using adopt open jdk8.
Can this source be compiled on Windows 10 ?

If I can compile on Linux, which distribution should I use?

**Comment by FrankHossfeld** [comment]
I would give GWT 2.9.0 a try.

**Comment by hpehl** [comment]
I'm closing this issue as this has yet to receive any input for over two years.
