### ISSUE TITLE
https://www.w3schools.com/tags/att_input_list.asp

### ISSUE THREAD

**Issue by oedemis** [hal/elemento#90]
Is there also support for datalist for intput ?

**Comment by hpehl** [comment]
Not explicitly. But you could use one of the builder methods in `Elements`: https://github.com/hal/elemento/blob/develop/core/src/main/java/org/jboss/elemento/Elements.java#L925

**Comment by hpehl** [comment]
Take a look at https://github.com/hal/elemento/blob/develop/core/src/main/java/org/jboss/elemento/Elements.java to get some inspiration. 
Don't hesitate to ask more question here.

**Comment by hpehl** [comment]
`<datalist>` is now supported by Elemento: https://hal.github.io/elemento/org/jboss/elemento/Elements.html#datalist()
